export const Users = [
  {
    id: 1,
    username: "Nitin Singh",
    top: "28px",
    left: "43px",
    transform: "scaleX(2.7) scaleY(2.2)",
  },
  {
    id: 2,
    username: "Nityanand",
    top: "30px",
    left: "1px",
    transform: "scaleX(3) scaleY(2.5)",
  },
  {
    id: 3,
    username: "Narayan Singh",
    top: "35px",
    left: "-52px",
    transform: "scaleX(3.5) scaleY(3)",
  },
  {
    id: 4,
    username: "Dholiya Pankaj",
    top: "-32px",
    left: "56px",
    transform: "scaleX(3.2) scaleY(2.8)",
  },
  {
    id: 5,
    username: "Gendaswami",
    top: "-35px",
    left: "20px",
    transform: "scaleX(4.5) scaleY(4)",
  },
  {
    id: 6,
    username: "Nitya Nor",
    top: "-37px",
    left: "-29px",
    transform: "scaleX(4.8) scaleY(4.3)",
  },
  {
    id: 7,
    username: "Pankaj Gupta",
    top: "-43px",
    left: "-95px",
    transform: "scaleX(6.5) scaleY(6)",
  },
  {
    id: 8,
    username: "Bachha Yadav",
    top: "-10px",
    left: "-174px",
    transform: "scaleX(18) scaleY(17)",
  },
  {
    id: 9,
    username: "Nanson Pod Dhar",
    top: "-10px",
    left: "105px",
    transform: "scaleX(18) scaleY(17)",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
